SELECT
	TAREA.TITULO AS TAREA,
	USUARIO.NOMBRE AS CREADOR,
	PROYECTO.NOMBRE AS PROYECTO
FROM
	TAREA
JOIN USUARIO ON TAREA.ID_USU_CREADOR = USUARIO.ID_USUARIO
JOIN PROYECTO ON TAREA.ID_PROYECTO = PROYECTO.ID_PROYECTO;
