SELECT
    USUARIO.NOMBRE AS USUARIO,
    EQUIPO.NOMBRE AS EQUIPO
FROM
    USUARIO
JOIN USUARIO_EQUIPO ON USUARIO.ID_USUARIO = USUARIO_EQUIPO.ID_USUARIO
JOIN EQUIPO ON USUARIO_EQUIPO.ID_EQUIPO = EQUIPO.ID_EQUIPO;
	ID_EQUIPO NUMBER(10),
	FOREIGN KEY(ID_USUARIO) REFERENCES USUARIO(ID_USUARIO),
	FOREIGN KEY(ID_EQUIPO) REFERENCES EQUIPO(ID_EQUIPO)
);

