<<<<<<< HEAD
CREATE TABLE USUARIO (
    ID_USUARIO INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(30) NOT NULL,
    EMAIL VARCHAR(100) UNIQUE NOT NULL,
    PASSWORD VARCHAR(30) NOT NULL,
    FECHA_REGISTRO DATE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE EQUIPO (
    ID_EQUIPO INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(30) NOT NULL,
    DESCRIPCION VARCHAR(100),
    FECHA_CREACION DATE,
    ID_USU_LIDER INT,
    FOREIGN KEY (ID_USU_LIDER) REFERENCES USUARIO(ID_USUARIO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE USUARIO_EQUIPO (
    ID_USUARIO INT,
    ID_EQUIPO INT,
    FECHA_UNION DATE,
    PRIMARY KEY (ID_USUARIO, ID_EQUIPO),
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO),
    FOREIGN KEY (ID_EQUIPO) REFERENCES EQUIPO(ID_EQUIPO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE PROYECTO (
    ID_PROYECTO INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(30) NOT NULL,
    DESCRIPCION VARCHAR(100),
    FECHA_INICIO DATE,
    FECHA_FIN DATE,
    ID_EQUIPO INT,
    FOREIGN KEY (ID_EQUIPO) REFERENCES EQUIPO(ID_EQUIPO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE ETIQUETA (
    ID_ETIQUETA INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(30) NOT NULL,
    ID_USUARIO INT,
    ID_EQUIPO INT,
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO),
    FOREIGN KEY (ID_EQUIPO) REFERENCES EQUIPO(ID_EQUIPO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE TAREA (
    ID_TAREA INT AUTO_INCREMENT PRIMARY KEY,
    TITULO VARCHAR(30) NOT NULL,
    DESCRIPCION VARCHAR(100),
    FECHA_CREACION DATE,
    FECHA_VENCIMIENTO DATE,
    ID_USU_CREADOR INT,
    ID_USU_ASIGNADO INT,
    ID_PROYECTO INT,
    FOREIGN KEY (ID_USU_CREADOR) REFERENCES USUARIO(ID_USUARIO),
    FOREIGN KEY (ID_USU_ASIGNADO) REFERENCES USUARIO(ID_USUARIO),
    FOREIGN KEY (ID_PROYECTO) REFERENCES PROYECTO(ID_PROYECTO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE TAREA_ETIQUETA (
    ID_TAREA INT,
    ID_ETIQUETA INT,
    PRIMARY KEY (ID_TAREA, ID_ETIQUETA),
    FOREIGN KEY (ID_TAREA) REFERENCES TAREA(ID_TAREA),
    FOREIGN KEY (ID_ETIQUETA) REFERENCES ETIQUETA(ID_ETIQUETA)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE COMENTARIO (
    ID_COMENTARIO INT AUTO_INCREMENT PRIMARY KEY,
    CONTENIDO VARCHAR(100) NOT NULL,
    FECHA_CREACION DATE,
    ID_USUARIO INT,
    ID_TAREA INT,
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO),
    FOREIGN KEY (ID_TAREA) REFERENCES TAREA(ID_TAREA)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
=======
--Tabla usuario
CREATE TABLE USUARIO(
	ID_USUARIO NUMBER(10) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	NOMBRE VARCHAR2(30) NOT NULL,
	EMAIL VARCHAR2(100) UNIQUE NOT NULL,
	PASSWORD VARCHAR2(30) NOT NULL,
	FECHA_REGISTRO DATE
);

--Tabla equipo
CREATE TABLE EQUIPO(
	ID_EQUIPO NUMBER(10) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	NOMBRE VARCHAR2(30) NOT NULL,
	DESCRIPCION VARCHAR2(100),
	FECHA_CREACION DATE,
	ID_USU_LIDER NUMBER(10),
	FOREIGN KEY(ID_USU_LIDER) REFERENCES USUARIO(ID_USUARIO)
);

--Tabla relacion usuario y equipo
CREATE TABLE USUARIO_EQUIPO(
	ID_USUARIO NUMBER(10),
	ID_EQUIPO NUMBER(10),
	FECHA_UNION DATE,
	PRIMARY KEY(ID_USUARIO, ID_EQUIPO),
	FOREIGN KEY(ID_USUARIO) REFERENCES USUARIO(ID_USUARIO),
	FOREIGN KEY(ID_EQUIPO) REFERENCES EQUIPO(ID_EQUIPO)
);

--Tabla proyecto
CREATE TABLE PROYECTO(
	ID_PROYECTO NUMBER(10) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	NOMBRE VARCHAR2(30) NOT NULL,
	DESCRIPCION VARCHAR2(100),
	FECHA_INICIO DATE,
	FECHA_FIN DATE,
	ID_EQUIPO NUMBER(10),
	FOREIGN KEY(ID_EQUIPO) REFERENCES EQUIPO(ID_EQUIPO)
);

--Tabla etiqueta
CREATE TABLE ETIQUETA(
	ID_ETIQUETA NUMBER(10) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	NOMBRE VARCHAR2(30) NOT NULL,
	ID_USUARIO NUMBER(10),
	ID_EQUIPO NUMBER(10),
	FOREIGN KEY(ID_USUARIO) REFERENCES USUARIO(ID_USUARIO),
	FOREIGN KEY(ID_EQUIPO) REFERENCES EQUIPO(ID_EQUIPO)
);

--Tabla tarea
CREATE TABLE TAREA(
	ID_TAREA NUMBER(10) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	TITULO VARCHAR2(30) NOT NULL,
	DESCRIPCION VARCHAR2(100),
	FECHA_CREACION DATE,
	FECHA_VENCIMIENTO DATE,
	ID_USU_CREADOR NUMBER(10),
	ID_USU_ASIGNADO NUMBER(10),
	ID_PROYECTO NUMBER(10),
	FOREIGN KEY(ID_USU_CREADOR) REFERENCES USUARIO(ID_USUARIO),
	FOREIGN KEY(ID_USU_ASIGNADO) REFERENCES USUARIO(ID_USUARIO),
	FOREIGN KEY(ID_PROYECTO) REFERENCES PROYECTO(ID_PROYECTO)
);

--Tabla tarea-etiqueta
CREATE TABLE TAREA_ETIQUETA(
	ID_TAREA NUMBER(10),
	ID_ETIQUETA NUMBER(10),
	PRIMARY KEY(ID_TAREA, ID_ETIQUETA),
	FOREIGN KEY(ID_TAREA) REFERENCES TAREA(ID_TAREA),
	FOREIGN KEY(ID_ETIQUETA) REFERENCES ETIQUETA(ID_ETIQUETA)
);

--Tabla de los comentarios
CREATE TABLE COMENTARIO(
	ID_COMENTARIO NUMBER(10) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	CONTENIDO VARCHAR2(100) NOT NULL,
	FECHA_CREACION DATE,
	ID_USUARIO NUMBER(10),
	ID_TAREA NUMBER(10),
	FOREIGN KEY(ID_USUARIO) REFERENCES USUARIO(ID_USUARIO),
	FOREIGN KEY(ID_TAREA) REFERENCES TAREA(ID_TAREA)
);

--INSERTS--
>>>>>>> parent of 3eeb122 (Conversión script Oracle -> MySQL para que funcion en phpmyadmin)

INSERT INTO USUARIO (NOMBRE, EMAIL, PASSWORD, FECHA_REGISTRO) VALUES
('Cristina', 'cristina@educamos.com', 'funcionaMal', NOW()),
('Ahri', 'gatita@vampirilla.com', 'colmillitos123', NOW()),
('Hada', 'hada@reboloncha.com', 'pollito456', NOW()),
('Juan Pérez', 'juan.perez@email.com', 'password123', '2023-01-15'),
('María García', 'maria.garcia@email.com', 'securepass456', '2023-02-20'),
('Carlos López', 'carlos.lopez@email.com', 'mypassword789', '2023-03-10'),
('Ana Torres', 'ana.torres@email.com', 'pass1234', '2023-04-01'),
('Luis Martínez', 'luis.martinez@email.com', 'securepass789', '2023-05-10'),
('Sofía Gómez', 'sofia.gomez@email.com', 'mypassword456', '2023-06-05');

INSERT INTO EQUIPO (NOMBRE, DESCRIPCION, FECHA_CREACION, ID_USU_LIDER) VALUES
('Equipo Michis', 'Equipo de desarrollo frontend', NOW(), 1);

INSERT INTO USUARIO_EQUIPO (ID_USUARIO, ID_EQUIPO, FECHA_UNION) VALUES
(1, 1, NOW()),
(2, 1, NOW()),
(3, 1, NOW());

INSERT INTO PROYECTO (NOMBRE, DESCRIPCION, FECHA_INICIO, FECHA_FIN, ID_EQUIPO) VALUES
('Proyecto Kanban', 'Hacer todo el trabajo o qué', NOW(), NULL, 1);

INSERT INTO ETIQUETA (NOMBRE, ID_USUARIO, ID_EQUIPO) VALUES
('Urgente', NULL, 1),
('Frontend', NULL, 1),
('Personal', 1, NULL);

INSERT INTO TAREA (TITULO, DESCRIPCION, FECHA_CREACION, FECHA_VENCIMIENTO, ID_USU_CREADOR, ID_USU_ASIGNADO, ID_PROYECTO) VALUES
('Crear vista Kanban', 'Diseñar e implementar todo el proyecto parece', NOW(), DATE_ADD(NOW(), INTERVAL 7 DAY), 1, 2, 1);

INSERT INTO TAREA_ETIQUETA (ID_TAREA, ID_ETIQUETA) VALUES
(1, 1),
(1, 2);

INSERT INTO COMENTARIO (CONTENIDO, FECHA_CREACION, ID_USUARIO, ID_TAREA) VALUES
('He comenzado con todo', NOW(), 2, 1);

