--Tabla usuario
CREATE TABLE USUARIO(
	ID_USUARIO NUMBER(10) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	NOMBRE VARCHAR2(30) NOT NULL,
	EMAIL VARCHAR2(100) UNIQUE NOT NULL,
	PASSWORD VARCHAR2(30) NOT NULL,
	FECHA_REGISTRO DATE
);

--Tabla equipo
CREATE TABLE EQUIPO(
	ID_EQUIPO NUMBER(10) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	NOMBRE VARCHAR2(30) NOT NULL,
	DESCRIPCION VARCHAR2(100),
	FECHA_CREACION DATE,
	ID_USU_LIDER NUMBER(10),
	FOREIGN KEY(ID_USU_LIDER) REFERENCES USUARIO(ID_USUARIO)
);

--Tabla relacion usuario y equipo
CREATE TABLE USUARIO_EQUIPO(
	ID_USUARIO NUMBER(10),
	ID_EQUIPO NUMBER(10),
	FECHA_UNION DATE,
	PRIMARY KEY(ID_USUARIO, ID_EQUIPO),
	FOREIGN KEY(ID_USUARIO) REFERENCES USUARIO(ID_USUARIO),
	FOREIGN KEY(ID_EQUIPO) REFERENCES EQUIPO(ID_EQUIPO)
);

--Tabla proyecto
CREATE TABLE PROYECTO(
	ID_PROYECTO NUMBER(10) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	NOMBRE VARCHAR2(30) NOT NULL,
	DESCRIPCION VARCHAR2(100),
	FECHA_INICIO DATE,
	FECHA_FIN DATE,
	ID_EQUIPO NUMBER(10),
	FOREIGN KEY(ID_EQUIPO) REFERENCES EQUIPO(ID_EQUIPO)
);

--Tabla etiqueta
CREATE TABLE ETIQUETA(
	ID_ETIQUETA NUMBER(10) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	NOMBRE VARCHAR2(30) NOT NULL,
	ID_USUARIO NUMBER(10),
	ID_EQUIPO NUMBER(10),
	FOREIGN KEY(ID_USUARIO) REFERENCES USUARIO(ID_USUARIO),
	FOREIGN KEY(ID_EQUIPO) REFERENCES EQUIPO(ID_EQUIPO)
);

--Tabla tarea
CREATE TABLE TAREA(
	ID_TAREA NUMBER(10) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	TITULO VARCHAR2(30) NOT NULL,
	DESCRIPCION VARCHAR2(100),
	FECHA_CREACION DATE,
	FECHA_VENCIMIENTO DATE,
	ID_USU_CREADOR NUMBER(10),
	ID_USU_ASIGNADO NUMBER(10),
	ID_PROYECTO NUMBER(10),
	FOREIGN KEY(ID_USU_CREADOR) REFERENCES USUARIO(ID_USUARIO),
	FOREIGN KEY(ID_USU_ASIGNADO) REFERENCES USUARIO(ID_USUARIO),
	FOREIGN KEY(ID_PROYECTO) REFERENCES PROYECTO(ID_PROYECTO)
);

--Tabla tarea-etiqueta
CREATE TABLE TAREA_ETIQUETA(
	ID_TAREA NUMBER(10),
	ID_ETIQUETA NUMBER(10),
	PRIMARY KEY(ID_TAREA, ID_ETIQUETA),
	FOREIGN KEY(ID_TAREA) REFERENCES TAREA(ID_TAREA),
	FOREIGN KEY(ID_ETIQUETA) REFERENCES ETIQUETA(ID_ETIQUETA)
);

--Tabla de los comentarios
CREATE TABLE COMENTARIO(
	ID_COMENTARIO NUMBER(10) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	CONTENIDO VARCHAR2(100) NOT NULL,
	FECHA_CREACION DATE,
	ID_USUARIO NUMBER(10),
	ID_TAREA NUMBER(10),
	FOREIGN KEY(ID_USUARIO) REFERENCES USUARIO(ID_USUARIO),
	FOREIGN KEY(ID_TAREA) REFERENCES TAREA(ID_TAREA)
);







--INSERTS--

INSERT INTO USUARIO (NOMBRE, EMAIL, PASSWORD, FECHA_REGISTRO)
VALUES ('Juan Pérez', 'juan.perez@email.com', 'password123', TO_DATE('2023-01-15', 'YYYY-MM-DD'));

INSERT INTO USUARIO (NOMBRE, EMAIL, PASSWORD, FECHA_REGISTRO)
VALUES ('María García', 'maria.garcia@email.com', 'securepass456', TO_DATE('2023-02-20', 'YYYY-MM-DD'));

INSERT INTO USUARIO (NOMBRE, EMAIL, PASSWORD, FECHA_REGISTRO)
VALUES ('Carlos López', 'carlos.lopez@email.com', 'mypassword789', TO_DATE('2023-03-10', 'YYYY-MM-DD'));

INSERT INTO EQUIPO (NOMBRE, DESCRIPCION, FECHA_CREACION, ID_USU_LIDER)
VALUES ('Equipo Desarrollo', 'Equipo de desarrollo de software', TO_DATE('2023-01-20', 'YYYY-MM-DD'), 1);

INSERT INTO EQUIPO (NOMBRE, DESCRIPCION, FECHA_CREACION, ID_USU_LIDER)
VALUES ('Equipo Diseño', 'Equipo de diseño UX/UI', TO_DATE('2023-02-25', 'YYYY-MM-DD'), 2);

INSERT INTO EQUIPO (NOMBRE, DESCRIPCION, FECHA_CREACION, ID_USU_LIDER)
VALUES ('Equipo QA', 'Equipo de control de calidad', TO_DATE('2023-03-15', 'YYYY-MM-DD'), 3);

INSERT INTO USUARIO_EQUIPO (ID_USUARIO, ID_EQUIPO, FECHA_UNION)
VALUES (1, 1, TO_DATE('2023-01-20', 'YYYY-MM-DD'));

INSERT INTO USUARIO_EQUIPO (ID_USUARIO, ID_EQUIPO, FECHA_UNION)
VALUES (2, 2, TO_DATE('2023-02-25', 'YYYY-MM-DD'));

INSERT INTO USUARIO_EQUIPO (ID_USUARIO, ID_EQUIPO, FECHA_UNION)
VALUES (3, 3, TO_DATE('2023-03-15', 'YYYY-MM-DD'));

INSERT INTO PROYECTO (NOMBRE, DESCRIPCION, FECHA_INICIO, FECHA_FIN)
VALUES ('App Móvil', 'Desarrollo de aplicación móvil', TO_DATE('2023-02-01', 'YYYY-MM-DD'), TO_DATE('2023-06-30', 'YYYY-MM-DD'));

INSERT INTO PROYECTO (NOMBRE, DESCRIPCION, FECHA_INICIO, FECHA_FIN)
VALUES ('Rediseño Web', 'Rediseño de la página web corporativa', TO_DATE('2023-03-01', 'YYYY-MM-DD'), TO_DATE('2023-05-31', 'YYYY-MM-DD'));

INSERT INTO PROYECTO (NOMBRE, DESCRIPCION, FECHA_INICIO, FECHA_FIN)
VALUES ('Pruebas Automatizadas', 'Implementación de pruebas automatizadas', TO_DATE('2023-04-01', 'YYYY-MM-DD'), TO_DATE('2023-07-31', 'YYYY-MM-DD'));

INSERT INTO ETIQUETA (NOMBRE, ID_USUARIO, ID_EQUIPO)
VALUES ('Urgente', 1, 1);

INSERT INTO ETIQUETA (NOMBRE, ID_USUARIO, ID_EQUIPO)
VALUES ('Diseño', 2, 2);

INSERT INTO ETIQUETA (NOMBRE, ID_USUARIO, ID_EQUIPO)
VALUES ('Bug', 3, 3);

INSERT INTO TAREA (TITULO, DESCRIPCION, FECHA_CREACION, FECHA_VENCIMIENTO)
VALUES ('Login Screen', 'Diseñar pantalla de login con validación de campos', TO_DATE('2023-02-10', 'YYYY-MM-DD'), TO_DATE('2023-02-28', 'YYYY-MM-DD'));

INSERT INTO TAREA (TITULO, DESCRIPCION, FECHA_CREACION, FECHA_VENCIMIENTO)
VALUES ('API Users', 'Desarrollar API REST para gestión de usuarios', TO_DATE('2023-03-05', 'YYYY-MM-DD'), TO_DATE('2023-03-20', 'YYYY-MM-DD'));

INSERT INTO TAREA (TITULO, DESCRIPCION, FECHA_CREACION, FECHA_VENCIMIENTO)
VALUES ('Test Login', 'Realizar pruebas funcionales del sistema de login', TO_DATE('2023-04-10', 'YYYY-MM-DD'), TO_DATE('2023-04-25', 'YYYY-MM-DD'));

INSERT INTO COMENTARIO (CONTENIDO, FECHA_CREACION)
VALUES ('He revisado el diseño, necesita ajustes en los colores', TO_DATE('2023-02-15', 'YYYY-MM-DD'));

INSERT INTO COMENTARIO (CONTENIDO, FECHA_CREACION)
VALUES ('API casi terminada, faltan algunos endpoints', TO_DATE('2023-03-10', 'YYYY-MM-DD'));

INSERT INTO COMENTARIO (CONTENIDO, FECHA_CREACION)
VALUES ('Encontrado bug al ingresar credenciales incorrectas', TO_DATE('2023-04-12', 'YYYY-MM-DD'));

INSERT INTO USUARIO (NOMBRE, EMAIL, PASSWORD, FECHA_REGISTRO)
VALUES ('Ana Torres', 'ana.torres@email.com', 'pass1234', TO_DATE('2023-04-01', 'YYYY-MM-DD'));

INSERT INTO USUARIO (NOMBRE, EMAIL, PASSWORD, FECHA_REGISTRO)
VALUES ('Luis Martínez', 'luis.martinez@email.com', 'securepass789', TO_DATE('2023-05-10', 'YYYY-MM-DD'));

INSERT INTO USUARIO (NOMBRE, EMAIL, PASSWORD, FECHA_REGISTRO)
VALUES ('Sofía Gómez', 'sofia.gomez@email.com', 'mypassword456', TO_DATE('2023-06-05', 'YYYY-MM-DD'));

INSERT INTO EQUIPO (NOMBRE, DESCRIPCION, FECHA_CREACION, ID_USU_LIDER)
VALUES ('Equipo Marketing', 'Equipo de marketing digital', TO_DATE('2023-04-15', 'YYYY-MM-DD'), 4);

INSERT INTO EQUIPO (NOMBRE, DESCRIPCION, FECHA_CREACION, ID_USU_LIDER)
VALUES ('Equipo Ventas', 'Equipo de ventas y atención al cliente', TO_DATE('2023-05-20', 'YYYY-MM-DD'), 5);

INSERT INTO EQUIPO (NOMBRE, DESCRIPCION, FECHA_CREACION, ID_USU_LIDER)
VALUES ('Equipo Soporte', 'Equipo de soporte técnico', TO_DATE('2023-06-25', 'YYYY-MM-DD'), 6);

INSERT INTO USUARIO_EQUIPO (ID_USUARIO, ID_EQUIPO, FECHA_UNION)
VALUES (4, 4, TO_DATE('2023-04-15', 'YYYY-MM-DD'));

INSERT INTO USUARIO_EQUIPO (ID_USUARIO, ID_EQUIPO, FECHA_UNION)
VALUES (5, 5, TO_DATE('2023-05-20', 'YYYY-MM-DD'));

INSERT INTO USUARIO_EQUIPO (ID_USUARIO, ID_EQUIPO, FECHA_UNION)
VALUES (6, 6, TO_DATE('2023-06-25', 'YYYY-MM-DD'));

INSERT INTO PROYECTO (NOMBRE, DESCRIPCION, FECHA_INICIO, FECHA_FIN)
VALUES ('Campaña SEO', 'Optimización de motores de búsqueda', TO_DATE('2023-05-01', 'YYYY-MM-DD'), TO_DATE('2023-08-31', 'YYYY-MM-DD'));

INSERT INTO PROYECTO (NOMBRE, DESCRIPCION, FECHA_INICIO, FECHA_FIN)
VALUES ('CRM Ventas', 'Implementación de sistema CRM', TO_DATE('2023-06-01', 'YYYY-MM-DD'), TO_DATE('2023-09-30', 'YYYY-MM-DD'));

INSERT INTO PROYECTO (NOMBRE, DESCRIPCION, FECHA_INICIO, FECHA_FIN)
VALUES ('Soporte 24/7', 'Establecimiento de soporte técnico continuo', TO_DATE('2023-07-01', 'YYYY-MM-DD'), TO_DATE('2023-10-31', 'YYYY-MM-DD'));

INSERT INTO ETIQUETA (NOMBRE, ID_USUARIO, ID_EQUIPO)
VALUES ('Prioridad Alta', 4, 4);

INSERT INTO ETIQUETA (NOMBRE, ID_USUARIO, ID_EQUIPO)
VALUES ('Cliente', 5, 5);

INSERT INTO ETIQUETA (NOMBRE, ID_USUARIO, ID_EQUIPO)
VALUES ('Soporte', 6, 6);

INSERT INTO TAREA (TITULO, DESCRIPCION, FECHA_CREACION, FECHA_VENCIMIENTO)
VALUES ('Landing Page', 'Diseñar página de aterrizaje para campaña', TO_DATE('2023-05-10', 'YYYY-MM-DD'), TO_DATE('2023-05-25', 'YYYY-MM-DD'));

INSERT INTO TAREA (TITULO, DESCRIPCION, FECHA_CREACION, FECHA_VENCIMIENTO)
VALUES ('Integración CRM', 'Configurar integración con sistema CRM', TO_DATE('2023-06-15', 'YYYY-MM-DD'), TO_DATE('2023-07-05', 'YYYY-MM-DD'));

INSERT INTO TAREA (TITULO, DESCRIPCION, FECHA_CREACION, FECHA_VENCIMIENTO)
VALUES ('Capacitación Soporte', 'Realizar capacitación para equipo de soporte', TO_DATE('2023-07-20', 'YYYY-MM-DD'), TO_DATE('2023-08-10', 'YYYY-MM-DD'));

INSERT INTO COMENTARIO (CONTENIDO, FECHA_CREACION)
VALUES ('La campaña SEO está mostrando buenos resultados iniciales', TO_DATE('2023-05-15', 'YYYY-MM-DD'));

INSERT INTO COMENTARIO (CONTENIDO, FECHA_CREACION)
VALUES ('El CRM ya está integrado, falta realizar pruebas', TO_DATE('2023-06-20', 'YYYY-MM-DD'));

INSERT INTO COMENTARIO (CONTENIDO, FECHA_CREACION)
VALUES ('El equipo de soporte está listo para operar 24/7', TO_DATE('2023-07-25', 'YYYY-MM-DD'));

INSERT INTO USUARIO (NOMBRE, EMAIL, PASSWORD, FECHA_REGISTRO)
VALUES ('Pedro Sánchez', 'pedro.sanchez@email.com', 'clavePedro', TO_DATE('2023-07-10', 'YYYY-MM-DD'));

INSERT INTO USUARIO (NOMBRE, EMAIL, PASSWORD, FECHA_REGISTRO)
VALUES ('Lucía Fernández', 'lucia.fernandez@email.com', 'lucia456', TO_DATE('2023-08-01', 'YYYY-MM-DD'));

INSERT INTO USUARIO (NOMBRE, EMAIL, PASSWORD, FECHA_REGISTRO)
VALUES ('Manuel Romero', 'manuel.romero@email.com', 'roma2023', TO_DATE('2023-09-12', 'YYYY-MM-DD'));

INSERT INTO EQUIPO (NOMBRE, DESCRIPCION, FECHA_CREACION, ID_USU_LIDER)
VALUES ('Equipo Innovación', 'Equipo de innovación tecnológica', TO_DATE('2023-08-10', 'YYYY-MM-DD'), 7);

INSERT INTO EQUIPO (NOMBRE, DESCRIPCION, FECHA_CREACION, ID_USU_LIDER)
VALUES ('Equipo Legal', 'Equipo de asesoría legal', TO_DATE('2023-09-05', 'YYYY-MM-DD'), 8);

INSERT INTO EQUIPO (NOMBRE, DESCRIPCION, FECHA_CREACION, ID_USU_LIDER)
VALUES ('Equipo RRHH', 'Recursos Humanos y talento', TO_DATE('2023-09-20', 'YYYY-MM-DD'), 9);

INSERT INTO USUARIO_EQUIPO (ID_USUARIO, ID_EQUIPO, FECHA_UNION)
VALUES (7, 7, TO_DATE('2023-08-10', 'YYYY-MM-DD'));

INSERT INTO USUARIO_EQUIPO (ID_USUARIO, ID_EQUIPO, FECHA_UNION)
VALUES (8, 8, TO_DATE('2023-09-05', 'YYYY-MM-DD'));

INSERT INTO USUARIO_EQUIPO (ID_USUARIO, ID_EQUIPO, FECHA_UNION)
VALUES (9, 9, TO_DATE('2023-09-20', 'YYYY-MM-DD'));

INSERT INTO PROYECTO (NOMBRE, DESCRIPCION, FECHA_INICIO, FECHA_FIN, ID_EQUIPO)
VALUES ('IA Predictiva', 'Proyecto de inteligencia artificial', TO_DATE('2023-08-15', 'YYYY-MM-DD'), TO_DATE('2023-12-15', 'YYYY-MM-DD'), 7);

INSERT INTO PROYECTO (NOMBRE, DESCRIPCION, FECHA_INICIO, FECHA_FIN, ID_EQUIPO)
VALUES ('Normativa RGPD', 'Adaptación legal a RGPD', TO_DATE('2023-09-10', 'YYYY-MM-DD'), TO_DATE('2023-11-30', 'YYYY-MM-DD'), 8);

INSERT INTO PROYECTO (NOMBRE, DESCRIPCION, FECHA_INICIO, FECHA_FIN, ID_EQUIPO)
VALUES ('Portal Empleo', 'Plataforma interna de empleos', TO_DATE('2023-10-01', 'YYYY-MM-DD'), TO_DATE('2024-01-31', 'YYYY-MM-DD'), 9);

INSERT INTO ETIQUETA (NOMBRE, ID_USUARIO, ID_EQUIPO)
VALUES ('Innovación', 7, 7);

INSERT INTO ETIQUETA (NOMBRE, ID_USUARIO, ID_EQUIPO)
VALUES ('Legal', 8, 8);

INSERT INTO ETIQUETA (NOMBRE, ID_USUARIO, ID_EQUIPO)
VALUES ('RRHH', 9, 9);

INSERT INTO TAREA (TITULO, DESCRIPCION, FECHA_CREACION, FECHA_VENCIMIENTO, ID_USU_CREADOR, ID_USU_ASIGNADO, ID_PROYECTO)
VALUES ('Análisis Datos', 'Análisis de patrones con IA', TO_DATE('2023-08-16', 'YYYY-MM-DD'), TO_DATE('2023-09-15', 'YYYY-MM-DD'), 7, 8, 10);

INSERT INTO TAREA (TITULO, DESCRIPCION, FECHA_CREACION, FECHA_VENCIMIENTO, ID_USU_CREADOR, ID_USU_ASIGNADO, ID_PROYECTO)
VALUES ('Revisión Legal', 'Auditoría interna de procesos', TO_DATE('2023-09-12', 'YYYY-MM-DD'), TO_DATE('2023-10-10', 'YYYY-MM-DD'), 8, 7, 11);

INSERT INTO TAREA (TITULO, DESCRIPCION, FECHA_CREACION, FECHA_VENCIMIENTO, ID_USU_CREADOR, ID_USU_ASIGNADO, ID_PROYECTO)
VALUES ('Publicar Oferta', 'Subir ofertas al portal de empleo', TO_DATE('2023-10-05', 'YYYY-MM-DD'), TO_DATE('2023-10-20', 'YYYY-MM-DD'), 9, 7, 12);

INSERT INTO COMENTARIO (CONTENIDO, FECHA_CREACION, ID_USUARIO, ID_TAREA)
VALUES ('Datos analizados, resultados prometedores', TO_DATE('2023-08-20', 'YYYY-MM-DD'), 7, 10);

INSERT INTO COMENTARIO (CONTENIDO, FECHA_CREACION, ID_USUARIO, ID_TAREA)
VALUES ('Revisión legal completada sin observaciones', TO_DATE('2023-09-18', 'YYYY-MM-DD'), 8, 11);

INSERT INTO COMENTARIO (CONTENIDO, FECHA_CREACION, ID_USUARIO, ID_TAREA)
VALUES ('Oferta publicada correctamente', TO_DATE('2023-10-07', 'YYYY-MM-DD'), 9, 12);


--consulta--

SELECT
    USUARIO.NOMBRE AS USUARIO,
    EQUIPO.NOMBRE AS EQUIPO
FROM
    USUARIO
JOIN USUARIO_EQUIPO ON USUARIO.ID_USUARIO = USUARIO_EQUIPO.ID_USUARIO
JOIN EQUIPO ON USUARIO_EQUIPO.ID_EQUIPO = EQUIPO.ID_EQUIPO;
	ID_EQUIPO NUMBER(10),
	FOREIGN KEY(ID_USUARIO) REFERENCES USUARIO(ID_USUARIO),
	FOREIGN KEY(ID_EQUIPO) REFERENCES EQUIPO(ID_EQUIPO)
);
