--Tabla usuario
CREATE TABLE USUARIO(
	ID_USUARIO NUMBER(10) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	NOMBRE VARCHAR2(30) NOT NULL,
	EMAIL VARCHAR2(100) UNIQUE NOT NULL,
	PASSWORD VARCHAR2(30) NOT NULL,
	FECHA_REGISTRO DATE
);

--Tabla equipo
CREATE TABLE EQUIPO(
	ID_EQUIPO NUMBER(10) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	NOMBRE VARCHAR2(30) NOT NULL,
	DESCRIPCION VARCHAR2(100),
	FECHA_CREACION DATE,
	ID_USU_LIDER NUMBER(10),
	FOREIGN KEY(ID_USU_LIDER) REFERENCES USUARIO(ID_USUARIO)
);

--Tabla relacion usuario y equipo
CREATE TABLE USUARIO_EQUIPO(
	ID_USUARIO NUMBER(10),
	ID_EQUIPO NUMBER(10),
	FECHA_UNION DATE,
	PRIMARY KEY(ID_USUARIO, ID_EQUIPO),
	FOREIGN KEY(ID_USUARIO) REFERENCES USUARIO(ID_USUARIO),
	FOREIGN KEY(ID_EQUIPO) REFERENCES EQUIPO(ID_EQUIPO)
);

--Tabla proyecto
CREATE TABLE PROYECTO(
	ID_PROYECTO NUMBER(10) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	NOMBRE VARCHAR2(30) NOT NULL,
	DESCRIPCION VARCHAR2(100),
	FECHA_INICIO DATE,
	FECHA_FIN DATE,
	ID_EQUIPO NUMBER(10),
	FOREIGN KEY(ID_EQUIPO) REFERENCES EQUIPO(ID_EQUIPO)
);

--Tabla etiqueta
CREATE TABLE ETIQUETA(
	ID_ETIQUETA NUMBER(10) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	NOMBRE VARCHAR2(30) NOT NULL,
	ID_USUARIO NUMBER(10),
	ID_EQUIPO NUMBER(10),
	FOREIGN KEY(ID_USUARIO) REFERENCES USUARIO(ID_USUARIO),
	FOREIGN KEY(ID_EQUIPO) REFERENCES EQUIPO(ID_EQUIPO)
);

--Tabla tarea
CREATE TABLE TAREA(
	ID_TAREA NUMBER(10) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	TITULO VARCHAR2(30) NOT NULL,
	DESCRIPCION VARCHAR2(100),
	FECHA_CREACION DATE,
	FECHA_VENCIMIENTO DATE,
	ID_USU_CREADOR NUMBER(10),
	ID_USU_ASIGNADO NUMBER(10),
	ID_PROYECTO NUMBER(10),
	FOREIGN KEY(ID_USU_CREADOR) REFERENCES USUARIO(ID_USUARIO),
	FOREIGN KEY(ID_USU_ASIGNADO) REFERENCES USUARIO(ID_USUARIO),
	FOREIGN KEY(ID_PROYECTO) REFERENCES PROYECTO(ID_PROYECTO)
);

--Tabla tarea-etiqueta
CREATE TABLE TAREA_ETIQUETA(
	ID_TAREA NUMBER(10),
	ID_ETIQUETA NUMBER(10),
	PRIMARY KEY(ID_TAREA, ID_ETIQUETA),
	FOREIGN KEY(ID_TAREA) REFERENCES TAREA(ID_TAREA),
	FOREIGN KEY(ID_ETIQUETA) REFERENCES ETIQUETA(ID_ETIQUETA)
);

--Tabla de los comentarios
CREATE TABLE COMENTARIO(
	ID_COMENTARIO NUMBER(10) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	CONTENIDO VARCHAR2(100) NOT NULL,
	FECHA_CREACION DATE,
	ID_USUARIO NUMBER(10),
	ID_TAREA NUMBER(10),
	FOREIGN KEY(ID_USUARIO) REFERENCES USUARIO(ID_USUARIO),
	FOREIGN KEY(ID_TAREA) REFERENCES TAREA(ID_TAREA)
);

--INSERTS--

INSERT INTO USUARIO (NOMBRE, EMAIL, PASSWORD, FECHA_REGISTRO) VALUES
('Cristina', 'cristina@educamos.com', 'funcionaMal', SYSDATE);

INSERT INTO USUARIO (NOMBRE, EMAIL, PASSWORD, FECHA_REGISTRO) VALUES
('Ahri', 'gatita@vampirilla.com', 'colmillitos123', SYSDATE);

INSERT INTO USUARIO (NOMBRE, EMAIL, PASSWORD, FECHA_REGISTRO) VALUES
('Hada', 'hada@reboloncha.com', 'pollito456', SYSDATE);

INSERT INTO EQUIPO (NOMBRE, DESCRIPCION, FECHA_CREACION, ID_USU_LIDER) VALUES
('Equipo Michis', 'Equipo de desarrollo frontend', SYSDATE, 1);

INSERT INTO USUARIO_EQUIPO (ID_USUARIO, ID_EQUIPO, FECHA_UNION) VALUES
(1, 1, SYSDATE);

INSERT INTO USUARIO_EQUIPO (ID_USUARIO, ID_EQUIPO, FECHA_UNION) VALUES
(2, 1, SYSDATE);

INSERT INTO USUARIO_EQUIPO (ID_USUARIO, ID_EQUIPO, FECHA_UNION) VALUES
(3, 1, SYSDATE);

INSERT INTO PROYECTO (NOMBRE, DESCRIPCION, FECHA_INICIO, FECHA_FIN, ID_EQUIPO) VALUES
('Proyecto Kanban', 'Hacer todo el trabajo o qué', SYSDATE, NULL, 1);

INSERT INTO ETIQUETA (NOMBRE, ID_USUARIO, ID_EQUIPO) VALUES
('Urgente', NULL, 1),
('Frontend', NULL, 1),
('Personal', 1, NULL);

INSERT INTO TAREA (TITULO, DESCRIPCION, FECHA_CREACION, FECHA_VENCIMIENTO, ID_USU_CREADOR, ID_USU_ASIGNADO, ID_PROYECTO) VALUES
('Crear vista Kanban', 'Diseñar e implementar todo el proyecto parece', SYSDATE, SYSDATE + 7, 1, 2, 1);

INSERT INTO TAREA_ETIQUETA (ID_TAREA, ID_ETIQUETA) VALUES
(1, 1);

INSERT INTO TAREA_ETIQUETA (ID_TAREA, ID_ETIQUETA) VALUES
(1, 2);

INSERT INTO COMENTARIO (CONTENIDO, FECHA_CREACION, ID_USUARIO, ID_TAREA) VALUES
('He comenzado con todo', SYSDATE, 2, 1);

INSERT INTO USUARIO (NOMBRE, EMAIL, PASSWORD, FECHA_REGISTRO)
VALUES ('Juan Pérez', 'juan.perez@email.com', 'password123', TO_DATE('2023-01-15', 'YYYY-MM-DD'));

INSERT INTO USUARIO (NOMBRE, EMAIL, PASSWORD, FECHA_REGISTRO)
VALUES ('María García', 'maria.garcia@email.com', 'securepass456', TO_DATE('2023-02-20', 'YYYY-MM-DD'));

INSERT INTO USUARIO (NOMBRE, EMAIL, PASSWORD, FECHA_REGISTRO)
VALUES ('Carlos López', 'carlos.lopez@email.com', 'mypassword789', TO_DATE('2023-03-10', 'YYYY-MM-DD'));

INSERT INTO USUARIO (NOMBRE, EMAIL, PASSWORD, FECHA_REGISTRO)
VALUES ('Ana Torres', 'ana.torres@email.com', 'pass1234', TO_DATE('2023-04-01', 'YYYY-MM-DD'));

INSERT INTO USUARIO (NOMBRE, EMAIL, PASSWORD, FECHA_REGISTRO)
VALUES ('Luis Martínez', 'luis.martinez@email.com', 'securepass789', TO_DATE('2023-05-10', 'YYYY-MM-DD'));

INSERT INTO USUARIO (NOMBRE, EMAIL, PASSWORD, FECHA_REGISTRO)
VALUES ('Sofía Gómez', 'sofia.gomez@email.com', 'mypassword456', TO_DATE('2023-06-05', 'YYYY-MM-DD'));

INSERT INTO EQUIPO (NOMBRE, DESCRIPCION, FECHA_CREACION, ID_USU_LIDER)
VALUES ('Equipo Desarrollo', 'Equipo de desarrollo de software', TO_DATE('2023-01-20', 'YYYY-MM-DD'), 1);

INSERT INTO EQUIPO (NOMBRE, DESCRIPCION, FECHA_CREACION, ID_USU_LIDER)
VALUES ('Equipo Diseño', 'Equipo de diseño UX/UI', TO_DATE('2023-02-25', 'YYYY-MM-DD'), 2);

INSERT INTO EQUIPO (NOMBRE, DESCRIPCION, FECHA_CREACION, ID_USU_LIDER)
VALUES ('Equipo QA', 'Equipo de control de calidad', TO_DATE('2023-03-15', 'YYYY-MM-DD'), 3);

INSERT INTO EQUIPO (NOMBRE, DESCRIPCION, FECHA_CREACION, ID_USU_LIDER)
VALUES ('Equipo Marketing', 'Equipo de marketing digital', TO_DATE('2023-04-15', 'YYYY-MM-DD'), 4);

INSERT INTO EQUIPO (NOMBRE, DESCRIPCION, FECHA_CREACION, ID_USU_LIDER)
VALUES ('Equipo Ventas', 'Equipo de ventas y atención al cliente', TO_DATE('2023-05-20', 'YYYY-MM-DD'), 5);

INSERT INTO EQUIPO (NOMBRE, DESCRIPCION, FECHA_CREACION, ID_USU_LIDER)
VALUES ('Equipo Soporte', 'Equipo de soporte técnico', TO_DATE('2023-06-25', 'YYYY-MM-DD'), 6);

INSERT INTO USUARIO_EQUIPO (ID_USUARIO, ID_EQUIPO, FECHA_UNION)
VALUES (1, 1, TO_DATE('2023-01-20', 'YYYY-MM-DD'));

INSERT INTO USUARIO_EQUIPO (ID_USUARIO, ID_EQUIPO, FECHA_UNION)
VALUES (2, 2, TO_DATE('2023-02-25', 'YYYY-MM-DD'));

INSERT INTO USUARIO_EQUIPO (ID_USUARIO, ID_EQUIPO, FECHA_UNION)
VALUES (3, 3, TO_DATE('2023-03-15', 'YYYY-MM-DD'));

INSERT INTO USUARIO_EQUIPO (ID_USUARIO, ID_EQUIPO, FECHA_UNION)
VALUES (4, 4, TO_DATE('2023-04-15', 'YYYY-MM-DD'));

INSERT INTO USUARIO_EQUIPO (ID_USUARIO, ID_EQUIPO, FECHA_UNION)
VALUES (5, 5, TO_DATE('2023-05-20', 'YYYY-MM-DD'));

INSERT INTO USUARIO_EQUIPO (ID_USUARIO, ID_EQUIPO, FECHA_UNION)
VALUES (6, 6, TO_DATE('2023-06-25', 'YYYY-MM-DD'));

INSERT INTO PROYECTO (NOMBRE, DESCRIPCION, FECHA_INICIO, FECHA_FIN)
VALUES ('App Móvil', 'Desarrollo de aplicación móvil', TO_DATE('2023-02-01', 'YYYY-MM-DD'), TO_DATE('2023-06-30', 'YYYY-MM-DD'));

INSERT INTO PROYECTO (NOMBRE, DESCRIPCION, FECHA_INICIO, FECHA_FIN)
VALUES ('Rediseño Web', 'Rediseño de la página web corporativa', TO_DATE('2023-03-01', 'YYYY-MM-DD'), TO_DATE('2023-05-31', 'YYYY-MM-DD'));

INSERT INTO PROYECTO (NOMBRE, DESCRIPCION, FECHA_INICIO, FECHA_FIN)
VALUES ('Pruebas Automatizadas', 'Implementación de pruebas automatizadas', TO_DATE('2023-04-01', 'YYYY-MM-DD'), TO_DATE('2023-07-31', 'YYYY-MM-DD'));

INSERT INTO PROYECTO (NOMBRE, DESCRIPCION, FECHA_INICIO, FECHA_FIN)
VALUES ('Campaña SEO', 'Optimización de motores de búsqueda', TO_DATE('2023-05-01', 'YYYY-MM-DD'), TO_DATE('2023-08-31', 'YYYY-MM-DD'));

INSERT INTO PROYECTO (NOMBRE, DESCRIPCION, FECHA_INICIO, FECHA_FIN)
VALUES ('CRM Ventas', 'Implementación de sistema CRM', TO_DATE('2023-06-01', 'YYYY-MM-DD'), TO_DATE('2023-09-30', 'YYYY-MM-DD'));

INSERT INTO PROYECTO (NOMBRE, DESCRIPCION, FECHA_INICIO, FECHA_FIN)
VALUES ('Soporte 24/7', 'Establecimiento de soporte técnico continuo', TO_DATE('2023-07-01', 'YYYY-MM-DD'), TO_DATE('2023-10-31', 'YYYY-MM-DD'));

INSERT INTO ETIQUETA (NOMBRE, ID_USUARIO, ID_EQUIPO)
VALUES ('Urgente', 1, 1);

INSERT INTO ETIQUETA (NOMBRE, ID_USUARIO, ID_EQUIPO)
VALUES ('Diseño', 2, 2);

INSERT INTO ETIQUETA (NOMBRE, ID_USUARIO, ID_EQUIPO)
VALUES ('Bug', 3, 3);

INSERT INTO ETIQUETA (NOMBRE, ID_USUARIO, ID_EQUIPO)
VALUES ('Prioridad Alta', 4, 4);

INSERT INTO ETIQUETA (NOMBRE, ID_USUARIO, ID_EQUIPO)
VALUES ('Cliente', 5, 5);

INSERT INTO ETIQUETA (NOMBRE, ID_USUARIO, ID_EQUIPO)
VALUES ('Soporte', 6, 6);

INSERT INTO TAREA (TITULO, DESCRIPCION, FECHA_CREACION, FECHA_VENCIMIENTO)
VALUES ('Login Screen', 'Diseñar pantalla de login con validación de campos', TO_DATE('2023-02-10', 'YYYY-MM-DD'), TO_DATE('2023-02-28', 'YYYY-MM-DD'));

INSERT INTO TAREA (TITULO, DESCRIPCION, FECHA_CREACION, FECHA_VENCIMIENTO)
VALUES ('API Users', 'Desarrollar API REST para gestión de usuarios', TO_DATE('2023-03-05', 'YYYY-MM-DD'), TO_DATE('2023-03-20', 'YYYY-MM-DD'));

INSERT INTO TAREA (TITULO, DESCRIPCION, FECHA_CREACION, FECHA_VENCIMIENTO)
VALUES ('Test Login', 'Realizar pruebas funcionales del sistema de login', TO_DATE('2023-04-10', 'YYYY-MM-DD'), TO_DATE('2023-04-25', 'YYYY-MM-DD'));

INSERT INTO TAREA (TITULO, DESCRIPCION, FECHA_CREACION, FECHA_VENCIMIENTO)
VALUES ('Landing Page', 'Diseñar página de aterrizaje para campaña', TO_DATE('2023-05-10', 'YYYY-MM-DD'), TO_DATE('2023-05-25', 'YYYY-MM-DD'));

INSERT INTO TAREA (TITULO, DESCRIPCION, FECHA_CREACION, FECHA_VENCIMIENTO)
VALUES ('Integración CRM', 'Configurar integración con sistema CRM', TO_DATE('2023-06-15', 'YYYY-MM-DD'), TO_DATE('2023-07-05', 'YYYY-MM-DD'));

INSERT INTO COMENTARIO (CONTENIDO, FECHA_CREACION)
VALUES ('He revisado el diseño, necesita ajustes en los colores', TO_DATE('2023-02-15', 'YYYY-MM-DD'));

INSERT INTO COMENTARIO (CONTENIDO, FECHA_CREACION)
VALUES ('API casi terminada, faltan algunos endpoints', TO_DATE('2023-03-10', 'YYYY-MM-DD'));

INSERT INTO COMENTARIO (CONTENIDO, FECHA_CREACION)
VALUES ('Encontrado bug al ingresar credenciales incorrectas', TO_DATE('2023-04-12', 'YYYY-MM-DD'));

